### ISSUE TITLE
How do you plant the drugs if you're using a different housing system?

### ISSUE THREAD

**Issue by Jwilliee** [qbcore-framework/qb-drugs#100]
It says area is not safe when I try to plant in my house

**Comment by tom-osborne** [comment]
You need to add a trigger to your housing script to trigger the weed event when entering your house
```lua
TriggerEvent('qb-weed:client:getHousePlants', house)
```

See here: https://github.com/qbcore-framework/qb-houses/blob/main/client/main.lua#L894
And here: https://github.com/qbcore-framework/qb-houses/blob/main/client/main.lua#L952

**Comment by Jwilliee** [comment]
Okay thank you!
