### ISSUE TITLE
[BUG] can't get number of available drugs when there's nothing left.

### ISSUE THREAD

**Issue by parham-tehrani** [qbcore-framework/qb-drugs#104]
when you start the corner selling and finish all your items.  the last part of the client side doesn't work
![image](https://user-images.githubusercontent.com/96952367/216441855-5cbea416-e99e-4869-83b7-aaf57a9eaf11.png)

**Comment by KhronicDemon** [comment]
I have the same issue I've tried fixing it without luck lol
