### ISSUE TITLE
Unable to recover stolen drugs

### ISSUE THREAD

**Issue by Ginjakz** [qbcore-framework/qb-drugs#106]
**Describe the bug**
When an NPC steals your last remaining drug(s) from you during Corner Seeling and you kill them and attempt to search ped, you get a box that comes up that you got your drugs back, but they are not added back to your inventory.

**To Reproduce**
1. Corner sell any available drug 1 at a time until you are robbed
2. Kill NPC
3. Use target to search ped
4. Drugs are not put back in inventory

**Expected behavior**
You should get your drugs back?  Works fine when you still have a supply in your inventory, only when its your last drug that was stolen from you

**Screenshots**
https://medal.tv/games/gta-v/clips/UO9GV4wTCl8xL/d1337GkCXyag?invite=cr-MSw2Sk4sNDIzOTEzNjks

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today with the lastest update (7013396 Fix when availableDrugs variable undefined (#105) - Sharkiiie)
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by Hutch93-png** [comment]
following, I noticed this too. didnt realize it was only when it was your last bag

**Comment by MentalIllness** [comment]
Should be fixed in the next PR
