### ISSUE TITLE
Script Error qb-drugs/client/deliveries.lua323: attmept to index a nil value (upvalue 'dealerCombo')

### ISSUE THREAD

**Issue by Zack3267** [qbcore-framework/qb-drugs#111]
Having this issue and unsure what to do.
Also says 
InitZones (qbdrugs/client/deliveries.lua:323)
ref (qbdrugs/client/deliveries.lua:19)

Any help is greatly appreciated!

**Comment by GodyFromDiscord** [comment]
Update your script, there has been multiple commits that have fixed this

**Comment by Z3rio** [comment]
This should already be fixed :)
