### ISSUE TITLE
Resolved.

### ISSUE THREAD

**Issue by Craigehton** [qbcore-framework/qb-drugs#112]

**Comment by GodyFromDiscord** [comment]
That is the time of day inbetween in which you can use the dealer

**Comment by Craigehton** [comment]
I know this, but it isn't working when I set it up. Nothing happens and I get no errors.

**Comment by BiGMAn0123** [comment]
same problem here too iv tried everything

**Comment by lMikki** [comment]
I have the same

**Comment by Save5Bucks** [comment]
remove the '#'
if Config.Dealers == 0 then return end
