### ISSUE TITLE
[BUG]When using /newdealer [dealername] [time1] [time2] , dealer is not in game.

### ISSUE THREAD

**Issue by Z3R0L0G1C** [qbcore-framework/qb-drugs#114]
**Describe the bug**
When using the /newdealer command in game the dealer is created in the database, no dealer is visible in game no menu interactions occurs. No error is generated, I also restarted the server and game client.

**To Reproduce**
1. run the /newdealer command
2. There is no dealer in game
3. check [DBNAME].dealers table and the dealers are generated in the database.

**Expected behavior**
A dealer to be created and menu to be available in game.

**Screenshots**
n/a

**Questions (please complete the following information):**
 - When you last updated: Created server from txAdmin receipe a week ago.
 - Are you using custom resource? which ones? All default qbcore receipe framework.
 - Have you renamed `qb-` to something custom? no

**Additional context**

Also when using the /dealergoto command works but still no dealer available.

**Comment by Z3R0L0G1C** [comment]
After some testing today, confirmed that removing 

`if #Config.Dealers == 0 then return end`
from 
`qb-drugs/client/deliveries.lua`

expected menu appears at dealers location.

**Comment by Save5Bucks** [comment]
remove the '#' 
if Config.Dealers == 0 then return end

**Comment by FrankPye** [comment]
Thank you so much

**Comment by hlh122138** [comment]
can't seem to find 

if #Config.Dealers == 0 then return end
from
qb-drugs/client/deliveries.lua

so I can remove it
