### ISSUE TITLE
[BUG] I cannot see what the offers are at all

### ISSUE THREAD

**Issue by Spydr999** [qbcore-framework/qb-drugs#118]
**Describe the bug**
Every time I go to sell either no offer shows or it shows for a split second making it very hard to read

**To Reproduce**
1. Start corner sell
2. Ped walks up to you

**Expected behavior**
Really needing help

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Last update
 - Are you using custom resource? which ones? I do have qb-target]
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by qb-core-dutch** [comment]
when a Ped walks up to you you need to target the ped if you have target on

**Comment by Spydr999** [comment]
What does that mean 3rd eye? If so I have done that and tried.

**Comment by Spydr999** [comment]
local Has target was off

**Comment by Spydr999** [comment]
The same thing happens with the dealer the message for E and G pop to quick to look at.
