### ISSUE TITLE
[BUG] Corner selling doesn't show notification of offer

### ISSUE THREAD

**Issue by MrRussianTV** [qbcore-framework/qb-drugs#121]
currently when you go to your radial menu and select "corner sell" when an AI walks up to you to buy drugs the notification for how much they want to buy and how much money they're offering does not show up, but you can still press "E" and accept the offer. the money and amount of drugs in your inventory does update, you just cant see how much they offer or how many drugs they want

**Comment by MrRussianTV** [comment]
NVMMMM My teleport script is directly interfering with those hud messages.

**Comment by Devexity-fivem** [comment]
how did u fix this im having this issue myself

**Comment by MrRussianTV** [comment]
> how did u fix this im having this issue myself

I deleted my Teleporting script because I realized QBCORE has one in small resources. I guess that other script interfered with my Player HUD and wouldn't let notifications through
