### ISSUE TITLE
[BUG] Police alerts not going out for corner selling drugs

### ISSUE THREAD

**Issue by IamCodyy** [qbcore-framework/qb-drugs#126]
**Describe the bug**
Corner selling does not alert the police, I've added prints in that bit of code and to no avail, no prints has shown in the console.

**To Reproduce**
1. Go to any popular location
2. Enable police chance high and start corner selling
3. Sell drugs

**Expected behavior**
A police alert sends out corner selling drugs

**Questions (please complete the following information):**
 - When you last updated: most recent
 - Have you renamed `qb-` to something custom? no

**Comment by GhzGarage** [comment]
Where did you add your print?

**Comment by IamCodyy** [comment]
> Where did you add your print?

I added one where the alert is supposed to trigger, and one inside the alert function. Perhaps I put it in the wrong place.
