### ISSUE TITLE
[SUGGESTION] Example of how to add dealer in config

### ISSUE THREAD

**Issue by Nophobia09** [qbcore-framework/qb-drugs#130]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
There isnt any guide on dealer paramaters in config. 

**Describe the feature you'd like**
A clear and concise description of what you want to happen. and with as much detail as possible how it would function in your opinion. Please try to keep it unique.
I have made an example.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered for people to have in mind just in case the main idea isn't liked but a derivative is.
None.

**Additional context**

```Lua
    Dealers = { 
        ['Sandy Dealer'] = {
            time = {min = 5, max = 23},
            name = "LiL Shady",
            coords = {x = 1894.4, y = 3895.88, z = 33.19},
            products = { 
                [1] = {
                    name = "weed_white-widow",
                    price = 15,
                    amount = 150,
                    info = {},
                    type = "item",
                    slot = 1,
                    minrep = 0,
                },
                [2] = {
                    name = "weed_skunk",
                    price = 15,
                    amount = 150,
                    info = {},
                    type = "item",
                    slot = 2,
                    minrep = 0,
                },
            },
    },

},
```

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-drugs/pull/133
