### ISSUE TITLE
Corner Selling

### ISSUE THREAD

**Issue by PrizonPony** [qbcore-framework/qb-drugs#24]
When Cornerselling is enabled, no peds walk up to you, but you get an accept/decline offer right away.

**Comment by Synthethics** [comment]
I can't seem to reproduce this. I've tried corner selling on a fresh build and it works normally, no accept/decline right away and NPC's come up to me normally. If you have edited the resource in any way to cause the issue, you can freely join [https://discord.gg/qbcore](QBCore's Support Discord).
