### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Slay3rIQ** [qbcore-framework/qb-drugs#25]
![image](https://user-images.githubusercontent.com/90642225/135099321-408dc6fb-aea0-49d5-8b07-8976ba807c67.png)

**Comment by Rhydium** [comment]
You have a configuration error.
Please join the [QBCore Discord](https://discord.gg/qbcore) for support.

**Comment by Slay3rIQ** [comment]
Ask multiple times but no help.
