### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by CrypticOG495** [qbcore-framework/qb-drugs#35]
This error occurs every time someone finishes a drug delivery. They do not receive any money and they do not gain any reputation

![mstsc_8Nkj0hdy6b](https://user-images.githubusercontent.com/94416125/141875402-1f9c4970-9d93-42df-ad09-f5e89a05f455.png)
![mstsc_aZSD26NzqH](https://user-images.githubusercontent.com/94416125/141875403-d9228ec6-88fd-4c0c-9da2-a9ece85e64a3.png)

**Comment by GhzGarage** [comment]
Fixed
