### ISSUE TITLE
lab keys

### ISSUE THREAD

**Issue by Drakoumelis** [qbcore-framework/qb-drugs#49]
how do i generate a lab key. there is a labkey in items.lua but whenever i try to spawn it it just throws me an error.

**Comment by PlanovskyJus** [comment]
> how do i generate a lab key. there is a labkey in items.lua but whenever i try to spawn it it just throws me an error.

There isn't an "items.lua" file in this script so this isnt relevent to this repo.

Lab key are/were used for a different script called qb-methlab which you may be able to find a version of, but you would have to code it up to date.

If you try to spawn something and it says "Item does not exist" you have to add it to the QBCore>shared>items.lua
