### ISSUE TITLE
Cornerselling to animals

### ISSUE THREAD

**Issue by Brusein** [qbcore-framework/qb-drugs#51]
Currently the code will sell to any ped including animals so drugs can be sold to cows (lol)

I'm not sure how to fix this myself, if I do code a fix I will share. 

![image](https://user-images.githubusercontent.com/97990422/155687934-7bc93cff-fab6-473c-a34e-e870ded5bfd2.png)

**Comment by F4RRUKO** [comment]
LOL Any fix for this ?

**Comment by Brusein** [comment]
> LOL Any fix for this ? 
> 
> For now I blacklisted Cow,Cat, and Rat peds.

Not worried about people abusing it as there are opportunities for the police to be alerted but don't want to deal with that on an RP server lol.

FYI being robbed by a cow is hilarious.

**Comment by L4wlz** [comment]
Did you add a temp fix since you have blacklisted Cow,Cat, and Rat peds?
