### ISSUE TITLE
Selling bug

### ISSUE THREAD

**Issue by nolanrp** [qbcore-framework/qb-drugs#63]
Cornerselling gets buggy sometimes. You will be selling and after your robbed no NPC's will approach you and the only way to fix is either relog or restart the script. It also happens if you don't stop selling when moving location.

**Comment by milotiro95** [comment]
Yes i have exactly the same problem when I'm into cornerselling mod if I'm entering a car it will not stop the script and stop count for the zone. The issue appear when we are more than 1 or 2 to sell on the server at the same time.

**Comment by milotiro95** [comment]
@BerkieBb do you have an idea about that ?
