### ISSUE TITLE
Drug locations 

### ISSUE THREAD

**Issue by IFoundMyDadPog** [qbcore-framework/qb-drugs#64]
im making a server suing your server files and i cant find all the drug loactions as i wanna change them around and Ive been looking in all the files and i could not find then i only found coke processing thats it i was woundering if you could help me find where they are and tell me how to change them?

**Comment by ThEmmanuelYt** [comment]
ye i also need help on this idk where to get the drugs and i cant seem to find them in the script, can you at least tell me the place where you found the process? maybe if i know the coke process i can help you

**Comment by POGGYPOGGY** [comment]
I am also having issues finding the drug locations? Please advise me

**Comment by squeaks1811** [comment]
Wheres the coke locations? Eg coke processing

**Comment by POGGYPOGGY** [comment]
What

**Comment by squeaks1811** [comment]
Someone said the found a coke processing location

**Comment by POGGYPOGGY** [comment]
Who are you and what are you speaking in reference to?

**Comment by squeaks1811** [comment]
The person who created the thread said they found a coke processing location

**Comment by POGGYPOGGY** [comment]
What script

**Comment by squeaks1811** [comment]
This one that ive commented on
