### ISSUE TITLE
This issue is happening frequently 

### ISSUE THREAD

**Issue by krizmatic** [qbcore-framework/qb-drugs#7]
![image](https://user-images.githubusercontent.com/58721529/124227192-e3622680-db27-11eb-9077-392ab2f76f91.png)

Some players are not able to buy drugs from the dealer. It will show the available amount, as soon they buy it the amount will get deducted and it is returned to the bank account. There inventory was almost empty, then also they couldn't buy it.

**Comment by GhzGarage** [comment]
Re-download and see if it’s fixed

**Comment by krizmatic** [comment]
The error in the console is not happening. But the other problem is still there.

**Comment by krizmatic** [comment]
To be specific, one person can buy drugs from only one drug location.
