### ISSUE TITLE
[BUG] Deliveries

### ISSUE THREAD

**Issue by Deksodija** [qbcore-framework/qb-drugs#76]
**Describe the bug**
When delivering drugs from a dealer in, the following error code shows up in the console when trying to deliver weed at the door: 
[  script:qb-drugs] SCRIPT ERROR: @qb-drugs/server/deliveries.lua:42: attempt to index a nil value (local 'deliveryData')

The weedbrick is not removed from the inventory, and no cash or rep is given out. Any idea? 

It is the latest qb-drugs from github, no changes made.

Made a new dealer with /newdealer command.

**Comment by loyal215** [comment]
Yea same problem here on what he said and I think it’s confusing

**Comment by GhzGarage** [comment]
Delivering without any errors on a fresh build as of tonight
