### ISSUE TITLE
[BUG] Issues adding dealers

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-drugs#78]
When I add a dealer in the game, I just get a poly box, and nothing else. After I type /dealers the name shows up, but the box is there still, and no person etc.

**Comment by peppinoita** [comment]
Disable the debug in the script

**Comment by TankinTom** [comment]
I don't see a debug option

**Comment by peppinoita** [comment]
In the client file

**Comment by TankinTom** [comment]
the only thing that mentions debug is in the cornerselling.lua in client, and it says debugPoly = false.
As stated, I've looked at every file, and it's eluding me.

**Comment by TankinTom** [comment]
So I redownloaded the entire qb-drugs, found debugpoly was set to true, changed it to false, and got the same issue
