### ISSUE TITLE
[BUG] stop selling drugs

### ISSUE THREAD

**Issue by amgmacht** [qbcore-framework/qb-drugs#80]
we have the problem that when you stop selling the drugs, the inventory doesn't open for a while or you can't use other things, but at some point it works again?

**Comment by IcebergQue** [comment]
> we have the problem that when you stop selling the drugs, the inventory doesn't open for a while or you can't use other things, but at some point it works again?

Do you like the script tho

**Comment by amgmacht** [comment]
Whats that for a question ? :D

I like the script, no question, it actually works very well except for the problem I described above.

**Comment by IcebergQue** [comment]
I'm thinking of checking it out

**Comment by GhzGarage** [comment]
Just tested tonight on a fresh build and inventory is locking/unlocking properly
