### ISSUE TITLE
[BUG] corner selling doesnt show notification of offer

### ISSUE THREAD

**Issue by NRTWraith** [qbcore-framework/qb-drugs#81]
currently when you go to your radial menu and select "corner sell" when an AI walks up to you to buy drugs the notification for how much they want to buy and how much money theyre offering does not show up, but you can still press "E" and accept the offer. the money and amount of drugs in your inventory does update, you just cant see how much they offer or how many drugs they want

**Comment by MentalIllness** [comment]
The bug should be fixed. I don't have this issue so if you experience this problem again, open a new issue.
