### ISSUE TITLE
[BUG] Dealer don't give you bricks

### ISSUE THREAD

**Issue by MrAg135** [qbcore-framework/qb-drugs#84]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to dealer
2. Start the mission
3. Just send you a massage but don't give you bricks to complete the order

**Expected behavior**
When I start the mission with Dealer , Dealer don't give me bricks to complete the order

**Questions (please complete the following information):**
 - When you last updated: Last update
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No
**Additional context**

**Comment by DannysRP** [comment]
I've noticed this issue as well. Also receive a server side error coming from qb-inventory/server/main.lua "attempt to call a nil value 'lower'" Then handler is server side of qb-drugs (when trying to add item)

**Comment by DannysRP** [comment]
![image](https://user-images.githubusercontent.com/88177315/185845209-5545d85d-07f7-4c38-855b-52b4c9a3171d.png)

**Comment by DannysRP** [comment]
![image](https://user-images.githubusercontent.com/88177315/185845792-fd9d318b-d9f8-436f-8bb8-86f13cf47f0a.png)

**Comment by DannysRP** [comment]
![image](https://user-images.githubusercontent.com/88177315/185845853-8e751574-e03d-4814-9ee7-8a6c2a570d89.png)

**Comment by CptNoHand** [comment]
I have the same
