### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ovi32** [qbcore-framework/qb-drugs#88]
**Describe the bug**
When i sell the last drug from my inventory it gives an error. It doesn't matter if the selling quantity is  1x or 10x. The moment all my drugs get sold out, it shows that upvalue error in F8 .

**To Reproduce**
1. Spawn couple of drugs to sell
2. Check F8 Console after selling all the drugs

**Screenshots**
https://cdn.discordapp.com/attachments/1001414024254210080/1012785237132071002/121.PNG

**Questions (please complete the following information):**
 - When you last updated: [Today]
 - Are you using custom resource? which ones? [NO]
 - Have you renamed `qb-` to something custom? [NO]

**Comment by Revline-RP** [comment]
Same here, even edited the code! You also can't sell anymore after this happens. Peds just walk by you!

**Comment by twigmasters** [comment]
Anyone find a fix for this yet? I am having the same issue
