### ISSUE TITLE
[BUG] Target does not work on robberypeds. 

### ISSUE THREAD

**Issue by byTrusty** [qbcore-framework/qb-drugs#93]
Target zone works on the ped, but nothing will come up as option if the ped moves even 1 step away from where they rob you. and considering they instantly start sprinting, they will move. the draw sprite for target stays in sale spot, zone moves, cant get drugs back.  Also error code for after selling/getting robbed of last drug item. (already an issue opened)

SALES WORK FINE. ROBBERY ONLY FOR TARGET.

1. Use Target.
2. Get Robbed.
3. Kill Ped.
4. Dont Get any options.

**Expected behavior**
Target option to get drugs back off robbery.

**Screenshots**
![image](https://user-images.githubusercontent.com/112107770/190870173-e6f1e596-2d93-4a2e-919d-81d4e9b0a7c0.png)
![image](https://user-images.githubusercontent.com/112107770/190870187-0309cc04-66d9-42f9-901e-6cbe4a99133e.png)

**Questions (please complete the following information):**
 - When you last updated: A couple times within the last month? just now switched to target.
 - Are you using custom resource? which ones?: No. qb-drugs and qb-target.
 - Have you renamed `qb-` to something custom? : No.

**Comment by MentalIllness** [comment]
Did you try it with the latest version?
