### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-drugs#95]
Didn't touch any of this files. Somehow when i started to do the drugs, I get this error,
![qbdrugs](https://user-images.githubusercontent.com/113321753/194955443-e9aa448d-18e7-4b12-afef-c676f527bca0.PNG)

**Comment by zwkf** [comment]
Closing this issue due to age and very little infromation provided.
Reopen if nessasary
